### ISSUE TITLE
update JavaFX to work against the recent GTK

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#16]
```
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[ERROR] Command errored: Paradigm Profiles Configurator
java.lang.UnsupportedOperationException: Internal Error
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:158)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:140)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:147)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:279)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:249)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:264)
        at cz.it4i.swing_javafx_ui.JavaFXRoutines.initRootAndController(JavaFXRoutines.java:48)
        at cz.it4i.swing_javafx_ui.JavaFXRoutines.initRootAndController(JavaFXRoutines.java:38)
        at cz.it4i.parallel.internal.ui.ParadigmScreenController.<init>(ParadigmScreenController.java:101)
        at cz.it4i.parallel.internal.ui.ParadigmScreenWindow.<init>(ParadigmScreenWindow.java:28)
        at cz.it4i.command.ParadigmProfilesManager.run(ParadigmProfilesManager.java:27)
        at org.scijava.command.CommandModule.run(CommandModule.java:196)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by xulman** [comment]
nevertheless, it works well on a different notebook (also Linux), with today's Fiji (which is with Zulu JRE) with the JavaFX

needs more testing, I guess....
