### ISSUE TITLE
more robust server side when scanning REMOTE working dir

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/parallel-macro#5]
if I leave any file in the remote working dir and that file's name is not parseable into integer, the client crashes creating a job because of
```
[ERROR] For input string: "script.sh"
java.lang.NumberFormatException: For input string: "script.sh"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at cz.it4i.cluster_job_launcher.ClusterJobLauncher.getLastJobIdFromRemoteWorkingDirectory(ClusterJobLauncher.java:343)
	at cz.it4i.fiji.ssh_hpc_client.SshHPCClient.createJob(SshHPCClient.java:133)
	at cz.it4i.fiji.ssh_hpc_client.SshHPCClient.createJob(SshHPCClient.java:62)
	at cz.it4i.fiji.hpc_adapter.HPCClientProxyAdapter.createJob(HPCClientProxyAdapter.java:60)
	at cz.it4i.fiji.hpc_adapter.HPCClientProxyAdapter.createJobSubmission(HPCClientProxyAdapter.java:50)
	at cz.it4i.fiji.hpc_adapter.Job.submitNewJob(Job.java:122)
	at cz.it4i.fiji.hpc_adapter.JobManager.createJob(JobManager.java:73)
	at cz.it4i.fiji.hpc_workflow.core.HPCWorkflowJobManager.createJob(HPCWorkflowJobManager.java:758)
	at cz.it4i.fiji.hpc_workflow.core.HPCWorkflowJobManager.createJob(HPCWorkflowJobManager.java:85)
	at cz.it4i.fiji.hpc_workflow.ui.HPCWorkflowControl.doCreateJob(HPCWorkflowControl.java:390)
	at cz.it4i.fiji.hpc_workflow.ui.HPCWorkflowControl.doJobAction(HPCWorkflowControl.java:356)
	at cz.it4i.fiji.hpc_workflow.ui.HPCWorkflowControl.lambda$null$42(HPCWorkflowControl.java:349)
	at cz.it4i.fiji.hpc_workflow.ui.HPCWorkflowControl.lambda$executeWSCallAsync$46(HPCWorkflowControl.java:424)
	at cz.it4i.swing_javafx_ui.JavaFXRoutines.lambda$executeAsync$4(JavaFXRoutines.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xulman** [comment]
avoid falling when discovering non-numbered folder.. 'cause this one shall never be considered anything HPCWfM-connected... you know

**Comment by velissarious** [comment]
Thank you for reporting the issue.

This issue has now been fixed and will be a part of the next release.

The issue was indeed as described and it was located in the `cluster_job_launcher` sub-project.
Now, non-integer named directories or files will be ignored by HPC Workflow Manager from now on. 
However, a warning will be printed. 

In general, no other files or directories should be present in the remote working directories except the job directories and their contents.
